### ISSUE TITLE
Credit?

### ISSUE THREAD

**Issue by nlscc** [xxxzsx/PyRipper#3]
It would be nice if you could give some credit to me... You seem to have just taken my code (https://github.com/nlscc/unpyarmor) and rebranded it as 'pyripper'?

**Comment by xxxzsx** [comment]
Do u care about 50 strings of your code that isn’t working well? :) Would be fine to hide this repo till i’ll have a time to make fancy tool, but stars would be lost. Happy new year and keep doing cool stuff, reference to your project added for some time.
